# Generated by Django 4.1.2 on 2022-11-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked',
            name='author',
            field=models.URLField(default='', max_length=255),
        ),
    ]
