# Generated by Django 3.1.6 on 2022-10-20 23:08

from django.db import migrations, models
import socialdistribution.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0004_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='object',
            field=models.JSONField(default=socialdistribution.models.default_list),
        ),
    ]
