# Generated by Django 3.1.6 on 2022-10-20 23:09

from django.db import migrations, models
import socialdistribution.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0006_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked',
            name='items',
            field=models.JSONField(default=socialdistribution.models.default_list),
        ),
    ]
