# Generated by Django 4.1.2 on 2022-10-22 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0009_inbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('author', models.CharField(max_length=60)),
                ('comment', models.TextField()),
                ('contentType', models.CharField(max_length=60)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.URLField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(default='', max_length=255)),
                ('id', models.URLField(max_length=255, primary_key=True, serialize=False)),
                ('source', models.URLField(max_length=255)),
                ('origin', models.URLField(max_length=255)),
                ('description', models.TextField(default='', max_length=255)),
                ('contentType', models.CharField(max_length=60)),
                ('content', models.TextField(blank=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('count', models.ImageField(blank=True, default=0, upload_to='')),
                ('visibility', models.CharField(default='PUBLIC', max_length=50)),
                ('unlisted', models.BooleanField(default='False')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
