# Generated by Django 4.1.2 on 2022-10-24 21:30

from django.db import migrations, models
import socialdistribution.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0010_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.JSONField(default=socialdistribution.models.default_list, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
