# Generated by Django 3.1.6 on 2022-10-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0010_author_admin_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.ImageField(upload_to=''),
        ),
    ]
