# Generated by Django 4.1.2 on 2022-10-25 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0011_post_categories_post_comments_alter_comment_comment'),
        ('socialdistribution', '0012_auto_20221021_0420'),
    ]

    operations = [
    ]
