# Generated by Django 4.1.2 on 2022-10-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0015_alter_post_comments_alter_post_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
