# Generated by Django 4.1.2 on 2022-10-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0016_alter_post_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='post',
            field=models.URLField(default='', max_length=255),
        ),
    ]
