# Generated by Django 4.1.2 on 2022-10-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0017_alter_followrequest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='followrequest',
            name='relation',
            field=models.CharField(default='N', max_length=50),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
