# Generated by Django 4.1.2 on 2022-10-28 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0018_alter_likes_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='post',
        ),
    ]
