# Generated by Django 4.1.2 on 2022-10-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0019_remove_likes_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='author',
            field=models.URLField(default='', max_length=255),
        ),
    ]
