# Generated by Django 4.1.2 on 2022-10-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0020_alter_likes_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='comment',
            field=models.CharField(default='', max_length=255),
        ),
    ]
