# Generated by Django 4.1.2 on 2022-10-30 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0020_alter_followrequest_id'),
        ('socialdistribution', '0021_likes_comment'),
    ]

    operations = [
    ]
