# Generated by Django 4.1.2 on 2022-10-31 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0022_merge_0020_alter_followrequest_id_0021_likes_comment'),
        ('socialdistribution', '0022_postimage'),
    ]

    operations = [
    ]
