# Generated by Django 4.1.2 on 2022-10-31 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0023_merge_20221031_0614'),
        ('socialdistribution', '0023_merge_20221031_2158'),
    ]

    operations = [
    ]
