# Generated by Django 4.1.2 on 2022-11-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0025_alter_post_contenttype_alter_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
