# Generated by Django 4.1.2 on 2022-11-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0024_alter_post_contenttype_alter_post_visibility'),
        ('socialdistribution', '0026_alter_author_password'),
    ]

    operations = [
    ]
