# Generated by Django 4.1.2 on 2022-11-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0027_merge_20221124_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.URLField(default='', max_length=255),
        ),
    ]
