# Generated by Django 4.1.2 on 2022-11-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0031_alter_inbox_author_alter_inbox_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='author',
            field=models.CharField(default='', max_length=256),
        ),
    ]
