# Generated by Django 3.2.7 on 2022-11-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0032_alter_inbox_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked',
            name='author',
            field=models.URLField(default='', max_length=255),
        ),
    ]
